config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root 'top_pages#home'
  get '/about' => 'top_pages#about'
  resources :users, only: [:show]
  resources :proposals, only: %i[show create destroy] do
    resources :reviews, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :file, FileUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 40 }
  validates :file, presence: true
  validate  :file_size

  private

  # アップロードされた画像のサイズをバリデーションする
  def file_size
    errors.add(:picture, '15MB未満である必要があります') if file.size > 15.megabytes
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :proposal
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :proposals, dependent: :destroy
  has_many :reviews, dependent: :destroy
  include Gravtastic
  gravtastic

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable, omniauth_providers: [:twitter]

  def self.from_omniauth(auth)
    find_or_initialize_by(provider: auth['provider'], uid: auth['uid']) do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.username = auth['info']['nickname']
      user.email = auth['info']['email']
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def current_user?(user)
    user == current_user
  end

  def item
    proposals
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, only: %i[edit update]

  def after_sign_in_path_for(_resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    added_attrs = %i[email username password password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end

  private

  def sign_in_required
    redirect_to new_user_session_url unless user_signed_in?
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def twitter
    @user = User.from_omniauth(request.env['omniauth.auth'].except('extra'))

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      @user.skip_confirmation!
      @user.save!
      sign_in_and_redirect @user
    end
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :authenticate_user!, only: %i[show create destroy]
  before_action :correct_user, only: :destroy

  def show
    @proposal = Proposal.find(params[:id])
    @review = Review.new
    @reviews = @proposal.reviews.order(created_at: :desc)
  end

  def create
    @proposal = current_user.proposals.build(proposal_params)
    if @proposal.save
      flash[:success] = 'ファイルをアップロードしました'
      redirect_to root_url
    else
      @feed_items = []
      render 'top_pages/home'
    end
  end

  def destroy
    @proposal.destroy
    flash[:success] = 'ファイルを削除しました'
    redirect_to request.referrer || root_url
  end

  private

  def proposal_params
    params.require(:proposal).permit(:content, :file)
  end

  def correct_user
    @proposal = current_user.proposals.find_by(id: params[:id])
    redirect_to root_url if @proposal.nil?
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :correct_user, only: :destroy

  def create
    @proposal = Proposal.find(params[:proposal_id])
    @review = Review.new(review_params)
    flash[:success] = if @review.save
                        'レビューしました'
                      else
                        '評価をつけてください。'
                      end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @review.destroy
    flash[:success] = 'レビューを削除しました'
    redirect_back(fallback_location: root_path)
  end

  private

  def review_params
    params.require(:review).permit(:text, :rate).merge(user_id: current_user.id, proposal_id: params[:proposal_id])
  end

  def correct_user
    @review = current_user.reviews.find_by(id: params[:id])
    redirect_to root_url if @review.nil?
  end
end

app/controllers/top_pages_controller.rb
# frozen_string_literal: true

class TopPagesController < ApplicationController
  before_action :sign_in_required, only: [:show]

  def home
    return unless user_signed_in?

    @proposal = current_user.proposals.build
    @all_items = Proposal.all.page(params[:page])
  end

  def about; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @current_user = User.find(params[:id])
    @proposals = @current_user.proposals.page(params[:page])
    @review = Review.new
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = 'My Proposal'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/top_pages_helper.rb
# frozen_string_literal: true

module TopPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= render 'partial/shim' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'partial/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'partial/footer' %>
    </div>
  </body>
</html>

app/views/partial/_all_proposals.html.erb
<% if @all_items.present? %>
  <ol class="proposals">
    <%= render @all_items %>
  </ol>
  <%= paginate @all_items %>
<% end %>

app/views/partial/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize(object.errors.count, "つエラーがあります") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/partial/_footer.html.erb
<footer class="footer">
  <small>
    The My Proposal
    by <a href="#">Jun Ishimaru</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "My Proposalとは", about_path %></li>
      <li><%= link_to "お問い合わせ", '#' %></li>
      <li><a href="#">お知らせ</a></li>
    </ul>
  </nav>
</footer>

app/views/partial/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "My Proposal", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "ホーム",   root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
          <ul class="dropdown-menu">
            <li><%= link_to "ユーザーページ",   current_user %></li>
            <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
            <li class="divider"></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            </li>
          </ul>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/partial/_proposal_form.html.erb
<%= form_for(@proposal) do |f| %>
  <%= render 'partial/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :content, placeholder: "企画書のタイトル..." %>
  </div>
  <span class="file">
    <%= f.file_field :file, accept: 'application/pdf' %>
  </span>
  <%= f.submit "投稿", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $('#proposal_file').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 15) {
      alert('最大ファイルサイズは15MBです。 小さいファイルを選択してください。');
    }
  });
</script>

app/views/partial/_review.html.erb
<h4>レビュー一覧</h4>
<% @reviews.each do |review| %>
  <div class="star-group">
    <%= image_tag current_user.gravatar_url(size: 50) %>
    <span class="user"><%= link_to review.user.username, review.user %></span>
    <div class="review-rating", id="star-view-<%= review.id %>">評価：</div>
    <span class="text">
      <%= review.text %>
    </span>
    <span class="timestamp">
      <%= time_ago_in_words(review.created_at) %>前にレビュー
      <% if current_user == review.user %>
        <%= link_to "レビューを削除", proposal_review_path(@proposal, review), method: :delete, 
                                            data: { confirm: "本当に削除しますか？" } %>
      <% end %>
    </span>
  </div>

  <script>
    $('#star-view-<%= review.id %>').raty({
      size: 38,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      half: true,
      readOnly: true,
      score: <%= review.rate %>,
    });
  </script>
<% end %>

app/views/partial/_review_form.html.erb
<%= form_for [@proposal, @review] do |f| %>
  <%= render 'partial/error_messages', object: f.object %>
  <div class="star-form-group" id="star">
    <%= f.label :rate,'評価：' %>
  </div>
  <div class="field">
    <label>コメント</label>
    <%= f.text_area :text, placeholder: "コメントがなくても、評価のみでレビューできます！" %><br>
  </div>
  <%= f.submit 'レビューを投稿する', class: "btn btn-primary" %>
<% end %>

<%= link_to "ホームへ戻る", root_path %>

<script>
    $('#star').raty({
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        scoreName: 'review[rate]',
        half: true,
    });
</script>

app/views/partial/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/partial/_user_info.html.erb
<span class="gravatar"><%= image_tag current_user.gravatar_url(size: 50) %></span>
<h1><%= current_user.username %></h1>
<span><%= link_to "プロフィール", current_user %></span>

app/views/proposals/_proposal.html.erb
<li id="proposal-<%= proposal.id %>">
  <%= image_tag current_user.gravatar_url(size: 50) %>
  <span class="user"><%= link_to proposal.user.username, proposal.user %></span>
  <span class="content">タイトル：<%= proposal.content %></span>
  <span class="file">
    <object data="<%= proposal.file.url %>" type="application/pdf" width="400" height="300" ></object>
  </span>
  <span class="timestamp">
    アップロード <%= time_ago_in_words(proposal.created_at) %>前
    <% if current_page?(proposal.user) %>
      <%= link_to "削除", proposal, method: :delete,
                                              data: { confirm: "本当に削除しますか？" } %>
    <% end %>
    <p><a href="/proposals/<%= proposal.id %>">この企画書をレビューする</a></p>
  </span>
</li>

app/views/proposals/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="micropost_form">
      <%= render 'partial/review_form' %>
    </section>
  </aside>
  <div class="col-md-8">
  <h1><%= @proposal.content %></h1>
    <span class="review-file">
      <object data="<%= @proposal.file.url %>" type="application/pdf" width="500" height="400" ></object>
    </span></br>
    <span class="review-timestamp">
      アップロード <%= time_ago_in_words(@proposal.created_at) %>前
    </span>
      <%= render 'partial/review' %>
  </div>
</div> 

app/views/top_pages/about.html.erb
<% provide(:title, "My Proposalとは") %>
<!DOCTYPE html>
  <div class="tab_container">
    <ul class="tab-list">
      <li class="tab box-active">概要</li>
      <li class="tab">MyProposalの使い方</li>
    </ul>
    <div class="tabbox-contents">
      <div class="tabbox box-show">
        <h1>My Proposalとは</h1>
        <div class="p-box">
          <p>ここは自分で考えた企画書をWEB上でお互いに評価し合うというサイトです。</p>
          <div class="list">  
            <p>・自分の企画が面白いかどうか色んな人に評価して欲しい</p>
            <p>・今自分の企画書に何が足りないかコメントして欲しい</p>
            <p>・他の人がどんな企画を考えているのか色々見て参考にしたい　　など</p>
          </div>
          <p> 学生、社会人問わず、様々な意見が飛び交うサイトとなっています。</p>
        </div>
      </div>
      <div class="tabbox">
        <h1>My Proposalの使い方</h1>
        <div class="how-to-use">
          <h3>①新規登録</h3>
          <p>サイトが表示されましたら、ヘッダー部にある「新規登録」かサイト下部にある「今すぐここから新規登録」ボタンをクリックします</p>
          <%= video_tag("/videos/move1.mp4", autoplay: :true, loop: :true, muted: :true, class: 'video-content') %>
        
          <h3>②登録方法</h3>
          <p>ユーザーネームとメールアドレス、パスワードを設定し、「ユーザー登録」ボタンをクリックします</p>
          <%= video_tag("/videos/move2.mp4", autoplay: :true, loop: :true, muted: :true, class: 'video-content') %>
        
          <h3>③本人確認のメール認証</h3>
          <p>入力したメールアドレス宛に本人確認メールが送信されますので、メール本文の「アカウント本登録」をクリックします</p>
          <%= image_tag src="image.png", class: 'video-content' %>
        
          <h3>④ログイン</h3>
          <p>認証メールからログイン画面に移りましたら、再度メールアドレスとパスワード入力して「ログイン」ボタンをクリックします</p>
          <%= video_tag("/videos/move3.mp4", autoplay: :true, loop: :true, muted: :true, class: 'video-content') %>

          <h3>⑤企画書投稿</h3>
          <p>投稿したい企画書を選択し、企画書のタイトルを入力して「投稿」ボタンをクリックします</p>
          <%= video_tag("/videos/move4.mp4", autoplay: :true, loop: :true, muted: :true, class: 'video-content') %>

          <h3>⑤レビュー</h3>
          <p>投稿されている企画書にはレビューすることができます</p>
          <p>星だけで評価することもできますが、積極的にコメントも残して企画書を評価し合いましょう</p>
          <%= video_tag("/videos/move5.mp4", autoplay: :true, loop: :true, muted: :true, class: 'video-content') %>
        </div>
      </div>
    </div>
  </div>
</html>

app/views/top_pages/home.html.erb
<% if user_signed_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'partial/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'partial/proposal_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h1>企画書一覧</h1>
      <%= render 'partial/all_proposals' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <%= image_tag src="top_image.png" %>
    <h1>お見合い企画書</h1>

    <h2>
      自分が考えた企画書をSNS上で評価し合ってみませんか？
    </h2>

    <div class="flex">
      <div>
        <%= image_tag src="icon_1.png" %>
        <h2>
          自分の考えた企画を見てもらいたい
        </h2>
      </div>

      <div>
        <%= image_tag src="icon_2.png" %>
        <h2>
          企画を手軽に公開
        </h2>
      </div>

      <div class="icon">
        <%= image_tag src="icon_3.png" %>
        <h2>
          色んな人から意見をもらおう
        </h2>
      </div>
    </div>

    <%= link_to "今すぐここから新規登録", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, current_user.username) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
      <span class="gravatar"><%= image_tag current_user.gravatar_url %></span>
        <%= @current_user.username %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <h1>投稿した企画書一覧</h1>
    <% if @current_user.proposals.any? %>
      <ol class="proposals">
        <%= render @proposals %>
      </ol>
      <%= paginate @proposals %>
    <% end %>
  </div>
</div>